-- TABELA MYSQL
DROP TABLE Dept cascade;
DROP TABLE Emp cascade;
CREATE DATABASE EMP;
USE EMP;

CREATE TABLE Dept (
    DEPTNO INT(2) PRIMARY KEY,
    DNAME VARCHAR(14),
    LOC VARCHAR(13)
);

CREATE TABLE Emp (
    empno INT(4) PRIMARY KEY,
    ename VARCHAR(10),
    job VARCHAR(9),
    mgr INT(4),
    hiredate DATE,
    sal FLOAT(7 , 2 ),
    comm FLOAT(7 , 2 ),
    deptno INT(2) REFERENCES Dept
); 

insert into dept values(         10 , 'ACCOUNTING'     , 'NEW YORK'      );
insert into dept values(         20 , 'RESEARCH'       , 'DALLAS'        );
insert into dept values(         30 , 'SALES'          , 'CHICAGO'       );
insert into dept values(         40 , 'OPERATIONS'     , 'BOSTON'        );

insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7369,'SMITH','CLERK',7902,STR_TO_DATE('17/02/1980',"%d/%m/%Y"),800,NULL,20);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7499,'ALLEN','SALESMAN',7698,STR_TO_DATE('20/02/1981',"%d/%m/%Y"),1600,300,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7521,'WARD','SALESMAN',7698,STR_TO_DATE('22/02/1981',"%d/%m/%Y"),1250,500,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7566,'JONES','MANAGER',7839,STR_TO_DATE('05/09/1981',"%d/%m/%Y"),2975,NULL,20);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7654,'MARTIN','SALESMAN',7698,STR_TO_DATE('28/09/1981',"%d/%m/%Y"),1250,1400,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7698,'BLAKE','MANAGER',7839,STR_TO_DATE('01/05/1981',"%d/%m/%Y"),2850,NULL,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7782,'CLARK','MANAGER',7839,STR_TO_DATE('09/06/1981',"%d/%m/%Y"),2450,NULL,10);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7788,'SCOTT','ANALYST',7566,STR_TO_DATE('19/04/1987',"%d/%m/%Y"),3000,NULL,20);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7839,'KING','PRESIDENT','',STR_TO_DATE('17/11/1981',"%d/%m/%Y"),5000,NULL,10);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7844,'TURNER','SALESMAN',7898,STR_TO_DATE('08/09/1981',"%d/%m/%Y"),1500,0,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7876,'ADAMS','CLERK',7788,STR_TO_DATE('23/05/1987',"%d/%m/%Y"),1100,NULL,20);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7900,'JAMES','CLERK',7698,STR_TO_DATE('03/12/1981',"%d/%m/%Y"),950,NULL,30);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7902,'FORD','ANALYST',7566,STR_TO_DATE('03/12/1981',"%d/%m/%Y"),3000,NULL,20);
Insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(7934,'MILLER','CLERK',7782,STR_TO_DATE('23/01/1982',"%d/%m/%Y"),1300,NULL,10);
--
select * from emp;
--
select * from EMPNO, ENAME, JOB, SAL where SAL >= 3000;
--
select distinct JOB as CARGOS from emp where SLA > 2000;
--
select * from DEPT;
--
select DNAME from DEPT where DEPTNO = 30;
--
update emp set SAL = 1300 where ENAME = 'SMITH';
-- OU
update emp set SAL = 1300 where ENAME = 7369;
--
select ENAME, JOB, SAL from emp order by SAL;
--
insert into emp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
Values(1200,'ANTÔNIO','SALES',7782,STR_TO_DATE('03/10/2022',"%d/%m/%Y"),2500,NULL,30);
--
SELECT EMPNO, ENAME, SAL, JOB FROM emp WHERE DEPTINO = 30 AND SAL < 2800;
--
UPDATE emp SET DEPTNO = 30 WHERE EMPNO = 7566;
--
DELETE FROM emp WHERE DPTNO = 10; 
--
SELECT ENAME, JOB, HIREDATE, SUBSTR(HIREDATE, 6, 5) AS DIA_MES, SUBSTR(HIREDATE, 6,2) MES,
SUBSTR(HIREDATE, 1, 7) MES_ANO FROM EMP;
--
SELECT ENAME, JOB, SUBSTR(JOB, 2, 4), SUBSTR(JOB, 2) FROM EMP;
--
SELECT EMPNO, ENAME, JOB, HIREDATE FROM EMP WHERE HIREDATE LIKE SUBSTR(HIREDATE, 6, 2) = '02';
--
SELECT ENAME, JOB, HIREDATE, HIREDATE + 10, HIREDATE - 42 FROM EMP;
--
SELECT ENAME, JOB, HIREDATE, SYSDATE() FROM EMP;
--
SELECT ENAME, HIREDATE, TIMESTAMPADD(MONTH, 8, HIREDATE) FROM EMP;
--
SELECT HIREDATE, DATE_FORMAT(HIREDATE, "%d/%m/%Y") AS DATA_FORMATADA
FROM EMP;
--
SELECT DEPTNO, MIN(SAL) AS "MENOR SALÁRIO", MAX(SAL) AS "MAIOR SALÁRIO", ROUND(AVG(SAL), 2) AS "MÉDIA SALÁRIO" FROM EMP GROUP BY DEPTNO;

SELECT ENAME, JOB, HIREDATE, truncate((SYSDATE - HIREDATE) / 7) AS SEMANAS FROM EMP;

SELECT DEPTNO, COUNT(*) "QTDE FUNC" FROM EMP GROUP BY DEPTNO;

SELECT JOB FROM EMP GROUP BY JOB;
-- OU
SELECT distinct JOB FROM EMP;

SELECT DEPTNO, SUM(SAL) "TOTAL SALÁRIO" FROM EMP;

SELECT JOB, SUM(SAL), MIN(SAL) FROM EMP GROUP BY JOB HAVING MIN(SAL) > 1400;

SELECT   DEPTNO, MIN(SAL)
FROM     EMP
WHERE    JOB <> ‘CLERK’ 
GROUP BY DEPTNO 
HAVING MIN(SAL)> 1500
ORDER BY DEPTNO DESC;

SELECT EMPNO, ENAME, JOB, SAL
FROM   EMP
WHERE  SAL = (SELECT MIN(SAL)FROM EMP);
 
 -- LISTA 6
SELECT DEPTNO, MAX(SAL)
FROM   EMP GROUP BY DEPTNO;

SELECT ENAME, SAL, DEPTNO
FROM   EMP WHERE SAL IN (2850, 3000, 5000) AND JOB = 'ANALYST';
-- OU
SELECT ENAME, SAL, DEPTNO, MAX(SAL)
FROM   EMP WHERE SAL = 2850 OR SAL = 3000 OR SAL = 5000;
 
SELECT ENAME, SAL, DEPTNO
FROM   EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT   ENAME, SAL, DEPTNO
FROM     EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY ENAME;

SELECT   ENAME, SAL, DEPTNO, JOB
FROM     EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE JOB = 'ANALYST' GROUP BY DEPTNO);
-- OU 
SELECT   ENAME, SAL, DEPTNO, JOB
FROM     EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO HAVING JOB = 'ANALYST');

SELECT JOB AS CARGOS, SUM(SAL) "TOTAL SALÁRIO" 
FROM EMP GROUP BY JOB ORDER BY JOB;

SELECT * FROM EMP WHERE ENAME = 'TURNER' OR ENAME = 'SMITH';
-- OU
SELECT * FROM EMP WHERE ENAME IN ('TURNER', 'SMITH');

 SELECT JOB, ROUND(AVG(SAL), 2) FROM EMP GROUP BY JOB;

UPDATE EMP SET SAL = 4000 WHERE ENAME =  'SMITH';

UPDATE EMP SET DEPTNO = 40 WHERE EMPNO = 7369;
-- OU
UPDATE EMP SET DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'OPERATIONS')
WHERE EMPNO = (SELECT EMPNO FROM EMP WHERE ENAME = 'SMITH');

SELECT DEPTNO, ROUND(AVG(SAL), 2) "MÉDIA SALARIAL", COUNT(*) "QTD FUNC" FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO, JOB, MIN(SAL), MAX(SAL), SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO;

DELETE FROM EMP WHERE HIREDATE LIKE '%87';
-- OU
DELETE FROM EMP WHERE HIREDATE LIKE '__/__/87';
-- OU
DELETE FROM EMP WHERE HIREDATE BETWEEN '01/01/87' AND '31/12/87';
-- OU
DELETE FROM EMP WHERE HIREDATE >= '01/01/87' AND HIREDATE <= '31/12/87';
ROLLBACK;

UPDATE EMP SET DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING') 
 WHERE EMPNO = 7900;

 SELECT ENAME, JOB, SAL, EMP.DEPTNO, DEPT.DEPTNO, DNAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO;
 
SELECT ENAME, JOB, SAL, EMP.DEPTNO, DEPT.DEPTNO, DNAME 
FROM EMP INNER JOIN DEPT 
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.SAL > 2000;

SELECT ENAME, JOB, SAL, EMP.DEPTNO, DEPT.DEPTNO, DNAME 
FROM EMP E INNER JOIN DEPT D 
ON EMP.DEPTNO = DEPT.DEPTNO;
-- OU
SELECT ENAME, JOB, SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E INNER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO;
-- OU
SELECT ENAME, JOB, SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO;

SELECT ENAME, E.JOB, E.SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E RIGHT OUTER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO;
-- OU
SELECT ENAME, E.JOB, E.SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E LEFT OUTER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO;

SELECT ENAME, E.JOB, E.SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E RIGHT OUTER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO
UNION
SELECT ENAME, E.JOB, E.SAL, E.DEPTNO, D.DEPTNO, D.DNAME 
FROM EMP E LEFT OUTER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO; 

-- LISTA 7
SELECT ENAME, SAL, DEPTNO FROM EMP WHERE HIREDATE LIKE '%81';


Commit;
